amazingCars=["BMW", "Lexus", "Ford", "Mercedes"];
console.log("Here are some amazing cars");
console.log(amazingCars);
console.log("Here's that list again, but this time with the last car removed");
amazingCars.pop();
console.log(amazingCars);
console.log("Here's the sorted version of the updated list:");
console.log(amazingCars.sort());
console.log("Here is the number of cars in the final list");
console.log(amazingCars.length);