var myFavoriteNumber=13;
var myFavoritePet='"Mandy Ann"';
var rainIsLovely=true;
var numberOne=24;
var numberTwo=57;
var addNumbers=numberOne+numberTwo;
var divideNumbers=numberOne/numberTwo;
console.log('myFavoriteNumber');
console.log(myFavoriteNumber);
console.log('myFavoritePet');
console.log(myFavoritePet);
console.log('rainIsLovely');
console.log(rainIsLovely);
console.log('numberOne');
console.log(numberOne);
console.log('numberTwo');
console.log(numberTwo);
console.log('addNumbers');
console.log(addNumbers);
console.log('divideNumbers');
console.log(divideNumbers);